# generated by datamodel-codegen:
#   filename:  document.json

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, ConfigDict


class Currency(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    code: Optional[str] = None
    decimals: Optional[int] = None
    local: Optional[str] = None
    name: Optional[str] = None
    symbol: Optional[str] = None
