# generated by datamodel-codegen:
#   filename:  document.json

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, ConfigDict


class Group(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    createdAt: Optional[str] = None
    currency: Optional[str] = None
    id: Optional[str] = None
    name: Optional[str] = None
    updatedAt: Optional[str] = None


class GroupStatistics(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    totalItemPrice: Optional[float] = None
    totalItems: Optional[int] = None
    totalLabels: Optional[int] = None
    totalLocations: Optional[int] = None
    totalUsers: Optional[int] = None
    totalWithWarranty: Optional[int] = None


class GroupUpdate(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    currency: Optional[str] = None
    name: Optional[str] = None


class TotalsByOrganizer(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: Optional[str] = None
    name: Optional[str] = None
    total: Optional[float] = None


class ValueOverTimeEntry(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    date: Optional[str] = None
    name: Optional[str] = None
    value: Optional[float] = None


class ValueOverTime(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    end: Optional[str] = None
    entries: Optional[List[ValueOverTimeEntry]] = None
    start: Optional[str] = None
    valueAtEnd: Optional[float] = None
    valueAtStart: Optional[float] = None


__all__ = [
    "Group",
    "GroupStatistics",
    "GroupUpdate",
    "TotalsByOrganizer",
    "ValueOverTimeEntry",
    "ValueOverTime",
]
