"""Pydantic models for Homebox group resource DTOs."""

# generated by datamodel-codegen:
#   filename:  document.json

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, ConfigDict


class Group(BaseModel):
    """API DTO for a Homebox group returned by the ``/v1/groups`` endpoint."""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    createdAt: Optional[str] = None
    currency: Optional[str] = None
    id: Optional[str] = None
    name: Optional[str] = None
    updatedAt: Optional[str] = None


class GroupStatistics(BaseModel):
    """Aggregate statistics for a group returned by the ``/v1/groups/statistics`` endpoint."""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    totalItemPrice: Optional[float] = None
    totalItems: Optional[int] = None
    totalLabels: Optional[int] = None
    totalLocations: Optional[int] = None
    totalUsers: Optional[int] = None
    totalWithWarranty: Optional[int] = None


class GroupUpdate(BaseModel):
    """Request payload for updating a group's name and/or currency."""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    currency: Optional[str] = None
    name: Optional[str] = None


class TotalsByOrganizer(BaseModel):
    """Aggregated total value for a single label or location organiser."""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: Optional[str] = None
    name: Optional[str] = None
    total: Optional[float] = None


class ValueOverTimeEntry(BaseModel):
    """A single data point in a time-series purchase-price report."""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    date: Optional[str] = None
    name: Optional[str] = None
    value: Optional[float] = None


class ValueOverTime(BaseModel):
    """Time-series purchase price report returned by the statistics endpoint."""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    end: Optional[str] = None
    entries: Optional[List[ValueOverTimeEntry]] = None
    start: Optional[str] = None
    valueAtEnd: Optional[float] = None
    valueAtStart: Optional[float] = None


__all__ = [
    "Group",
    "GroupStatistics",
    "GroupUpdate",
    "TotalsByOrganizer",
    "ValueOverTimeEntry",
    "ValueOverTime",
]
