"""Pydantic models for Homebox item resource DTOs."""

# generated by datamodel-codegen:
#   filename:  document.json

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, ConfigDict, Field, model_validator

from .attachment import Attachment
from .group import Group
from .locations import Location, LocationSummary
from .maintenance import MaintenanceEntry
from .tags import Tag, TagSummary
from .types import ItemFieldType, ItemType


class Item(BaseModel):
    """Internal ORM entity representing a Homebox inventory item."""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    archived: Optional[bool] = Field(default=None, description='Archived holds the value of the "archived" field.')
    asset_id: Optional[int] = Field(default=None, description='AssetID holds the value of the "asset_id" field.')
    created_at: Optional[str] = Field(default=None, description='CreatedAt holds the value of the "created_at" field.')
    description: Optional[str] = Field(
        default=None,
        description='Description holds the value of the "description" field.',
    )
    edges: Optional[ItemEdges] = Field(
        default=None,
        description="Edges holds the relations/edges for other nodes in the graph.\nThe values are being populated by the ItemQuery when eager-loading is set.",
    )
    id: Optional[str] = Field(default=None, description="ID of the ent.")
    import_ref: Optional[str] = Field(default=None, description='ImportRef holds the value of the "import_ref" field.')
    insured: Optional[bool] = Field(default=None, description='Insured holds the value of the "insured" field.')
    lifetime_warranty: Optional[bool] = Field(
        default=None,
        description='LifetimeWarranty holds the value of the "lifetime_warranty" field.',
    )
    manufacturer: Optional[str] = Field(
        default=None,
        description='Manufacturer holds the value of the "manufacturer" field.',
    )
    model_number: Optional[str] = Field(
        default=None,
        description='ModelNumber holds the value of the "model_number" field.',
    )
    name: Optional[str] = Field(default=None, description='Name holds the value of the "name" field.')
    notes: Optional[str] = Field(default=None, description='Notes holds the value of the "notes" field.')
    purchase_from: Optional[str] = Field(
        default=None,
        description='PurchaseFrom holds the value of the "purchase_from" field.',
    )
    purchase_price: Optional[float] = Field(
        default=None,
        description='PurchasePrice holds the value of the "purchase_price" field.',
    )
    purchase_time: Optional[str] = Field(
        default=None,
        description='PurchaseTime holds the value of the "purchase_time" field.',
    )
    quantity: Optional[float] = Field(default=None, description='Quantity holds the value of the "quantity" field.')
    serial_number: Optional[str] = Field(
        default=None,
        description='SerialNumber holds the value of the "serial_number" field.',
    )
    sold_notes: Optional[str] = Field(default=None, description='SoldNotes holds the value of the "sold_notes" field.')
    sold_price: Optional[float] = Field(
        default=None, description='SoldPrice holds the value of the "sold_price" field.'
    )
    sold_time: Optional[str] = Field(default=None, description='SoldTime holds the value of the "sold_time" field.')
    sold_to: Optional[str] = Field(default=None, description='SoldTo holds the value of the "sold_to" field.')
    sync_child_items_locations: Optional[bool] = Field(
        default=None,
        description='SyncChildItemsLocations holds the value of the "sync_child_items_locations" field.',
    )
    updated_at: Optional[str] = Field(default=None, description='UpdatedAt holds the value of the "updated_at" field.')
    warranty_details: Optional[str] = Field(
        default=None,
        description='WarrantyDetails holds the value of the "warranty_details" field.',
    )
    warranty_expires: Optional[str] = Field(
        default=None,
        description='WarrantyExpires holds the value of the "warranty_expires" field.',
    )


class ItemEdges(BaseModel):
    """Graph edges for the Item ORM entity."""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    attachments: Optional[List[Attachment]] = Field(
        default=None, description="Attachments holds the value of the attachments edge."
    )
    children: Optional[List[Item]] = Field(default=None, description="Children holds the value of the children edge.")
    fields: Optional[List[ItemField]] = Field(default=None, description="Fields holds the value of the fields edge.")
    group: Optional[Group] = Field(default=None, description="Group holds the value of the group edge.")
    tag: Optional[List[Tag]] = Field(default=None, description="Tag holds the value of the tag edge.")
    location: Optional[Location] = Field(default=None, description="Location holds the value of the location edge.")
    maintenance_entries: Optional[List[MaintenanceEntry]] = Field(
        default=None,
        description="MaintenanceEntries holds the value of the maintenance_entries edge.",
    )
    parent: Optional[Item] = Field(default=None, description="Parent holds the value of the parent edge.")


class ItemField(BaseModel):
    """Internal ORM entity representing a custom field on an item."""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    boolean_value: Optional[bool] = Field(
        default=None,
        description='BooleanValue holds the value of the "boolean_value" field.',
    )
    created_at: Optional[str] = Field(default=None, description='CreatedAt holds the value of the "created_at" field.')
    description: Optional[str] = Field(
        default=None,
        description='Description holds the value of the "description" field.',
    )
    edges: Optional[ItemFieldEdges] = Field(
        default=None,
        description="Edges holds the relations/edges for other nodes in the graph.\nThe values are being populated by the ItemFieldQuery when eager-loading is set.",
    )
    id: Optional[str] = Field(default=None, description="ID of the ent.")
    name: Optional[str] = Field(default=None, description='Name holds the value of the "name" field.')
    number_value: Optional[int] = Field(
        default=None,
        description='NumberValue holds the value of the "number_value" field.',
    )
    text_value: Optional[str] = Field(default=None, description='TextValue holds the value of the "text_value" field.')
    time_value: Optional[str] = Field(default=None, description='TimeValue holds the value of the "time_value" field.')
    type: Optional[ItemFieldType] = Field(default=None, description='Type holds the value of the "type" field.')
    updated_at: Optional[str] = Field(default=None, description='UpdatedAt holds the value of the "updated_at" field.')


class ItemFieldEdges(BaseModel):
    """Graph edges for the ItemField ORM entity."""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    item: Optional[Item] = Field(default=None, description="Item holds the value of the item edge.")


class DuplicateOptions(BaseModel):
    """Options for the duplicate-item operation."""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    copyAttachments: Optional[bool] = None
    copyCustomFields: Optional[bool] = None
    copyMaintenance: Optional[bool] = None
    copyPrefix: Optional[str] = None


class ItemAttachment(BaseModel):
    """API DTO for an item attachment returned by item detail endpoints."""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    createdAt: Optional[str] = None
    id: Optional[str] = None
    mimeType: Optional[str] = None
    path: Optional[str] = None
    primary: Optional[bool] = None
    thumbnail: Optional[Attachment] = None
    title: Optional[str] = None
    type: Optional[str] = None
    updatedAt: Optional[str] = None


class ItemAttachmentUpdate(BaseModel):
    """Payload for updating an item attachment's metadata."""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    primary: Optional[bool] = None
    title: Optional[str] = None
    type: Optional[str] = None


class ItemFieldUpdate(BaseModel):
    """Payload for creating or updating a custom field on an item."""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    booleanValue: Optional[bool] = None
    id: Optional[str] = None
    name: Optional[str] = None
    numberValue: Optional[int] = None
    textValue: Optional[str] = None
    type: Optional[str] = None


class ItemCreate(BaseModel):
    """Request payload for creating a new item."""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    description: Optional[str] = Field(default=None, max_length=1000)
    tagIds: Optional[List[str]] = None
    labelIds: Optional[List[str]] = None
    locationId: Optional[str] = Field(default=None, description="Edges")
    name: str = Field(..., min_length=1, max_length=255)
    parentId: Optional[str] = None
    quantity: Optional[float] = None


class ItemPatch(BaseModel):
    """Payload for a partial item update (location, labels, or quantity)."""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: Optional[str] = None
    tagIds: Optional[List[str]] = None
    labelIds: Optional[List[str]] = None
    locationId: Optional[str] = None
    quantity: Optional[float] = None


class ItemUpdate(BaseModel):
    """Request payload for a full item update (all editable fields)."""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    archived: Optional[bool] = None
    assetId: Optional[str] = None
    description: Optional[str] = Field(default=None, max_length=1000)
    fields: Optional[List[ItemFieldUpdate]] = None
    id: Optional[str] = None
    insured: Optional[bool] = None
    tagIds: Optional[List[str]] = None
    labelIds: Optional[List[str]] = None
    lifetimeWarranty: Optional[bool] = Field(default=None, description="Warranty")
    locationId: Optional[str] = Field(default=None, description="Edges")
    manufacturer: Optional[str] = None
    modelNumber: Optional[str] = None
    name: str = Field(..., min_length=1, max_length=255)
    notes: Optional[str] = Field(default=None, description="Extras")
    parentId: Optional[str] = None
    purchaseFrom: Optional[str] = Field(default=None, max_length=255)
    purchasePrice: Optional[float] = None
    purchaseTime: Optional[str] = Field(default=None, description="Purchase")
    quantity: Optional[float] = None
    serialNumber: Optional[str] = Field(default=None, description="Identifications")
    soldNotes: Optional[str] = None
    soldPrice: Optional[float] = None
    soldTime: Optional[str] = Field(default=None, description="Sold")
    soldTo: Optional[str] = Field(default=None, max_length=255)
    syncChildItemsLocations: Optional[bool] = None
    warrantyDetails: Optional[str] = None
    warrantyExpires: Optional[str] = None


class ItemSummary(BaseModel):
    """Lightweight item representation used in list / pagination responses."""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    archived: Optional[bool] = None
    assetId: Optional[str] = Field(default=None, examples=["0"])
    createdAt: Optional[str] = None
    description: Optional[str] = None
    id: Optional[str] = None
    imageId: Optional[str] = None
    insured: Optional[bool] = None
    tags: Optional[List[TagSummary]] = None
    labels: Optional[List[TagSummary]] = None
    location: Optional[LocationSummary] = Field(default=None, description="Edges")
    name: Optional[str] = None
    purchasePrice: Optional[float] = None
    quantity: Optional[float] = None
    soldTime: Optional[str] = Field(default=None, description="Sale details")
    thumbnailId: Optional[str] = None
    updatedAt: Optional[str] = None

    @model_validator(mode="before")
    @classmethod
    def _sync_legacy_labels(cls, data):
        """Backfill ``labels`` from ``tags`` when only tag data is returned."""
        if isinstance(data, dict) and "labels" not in data and "tags" in data:
            data["labels"] = data["tags"]
        return data


class ItemOut(BaseModel):
    """Full item representation returned by item detail and mutation endpoints."""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    archived: Optional[bool] = None
    assetId: Optional[str] = Field(default=None, examples=["0"])
    attachments: Optional[List[ItemAttachment]] = None
    createdAt: Optional[str] = None
    description: Optional[str] = None
    fields: Optional[List[ItemFieldUpdate]] = None
    id: Optional[str] = None
    imageId: Optional[str] = None
    insured: Optional[bool] = None
    tags: Optional[List[TagSummary]] = None
    labels: Optional[List[TagSummary]] = None
    lifetimeWarranty: Optional[bool] = Field(default=None, description="Warranty")
    location: Optional[LocationSummary] = Field(default=None, description="Edges")
    manufacturer: Optional[str] = None
    modelNumber: Optional[str] = None
    name: Optional[str] = None
    notes: Optional[str] = Field(default=None, description="Extras")
    parent: Optional[ItemSummary] = None
    purchaseFrom: Optional[str] = None
    purchasePrice: Optional[float] = None
    purchaseTime: Optional[str] = Field(default=None, description="Purchase")
    quantity: Optional[float] = None
    serialNumber: Optional[str] = None
    soldNotes: Optional[str] = None
    soldPrice: Optional[float] = None
    soldTime: Optional[str] = Field(default=None, description="Sold")
    soldTo: Optional[str] = None
    syncChildItemsLocations: Optional[bool] = None
    thumbnailId: Optional[str] = None
    updatedAt: Optional[str] = None
    warrantyDetails: Optional[str] = None
    warrantyExpires: Optional[str] = None

    @model_validator(mode="before")
    @classmethod
    def _sync_legacy_labels(cls, data):
        """Backfill ``labels`` from ``tags`` when only tag data is returned."""
        if isinstance(data, dict) and "labels" not in data and "tags" in data:
            data["labels"] = data["tags"]
        return data


class ItemPath(BaseModel):
    """A single node in an item's ancestry path (breadcrumb)."""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: Optional[str] = None
    name: Optional[str] = None
    type: Optional[ItemType] = None


class PaginationResultRepoItemSummary(BaseModel):
    """Paginated result wrapper for item summary lists."""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    items: Optional[List[ItemSummary]] = None
    page: Optional[int] = None
    pageSize: Optional[int] = None
    total: Optional[int] = None


Item.model_rebuild(raise_errors=False)
ItemEdges.model_rebuild(raise_errors=False)
ItemField.model_rebuild(raise_errors=False)

__all__ = [
    "DuplicateOptions",
    "ItemAttachment",
    "ItemAttachmentUpdate",
    "ItemFieldUpdate",
    "ItemCreate",
    "ItemPatch",
    "ItemType",
    "ItemUpdate",
    "ItemSummary",
    "ItemOut",
    "ItemPath",
    "PaginationResultRepoItemSummary",
]
