"""Pydantic models for Homebox location resource DTOs."""

# generated by datamodel-codegen:
#   filename:  document.json

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, ConfigDict, Field

from .group import Group


class Location(BaseModel):
    """Internal ORM entity representing a Homebox storage location."""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    created_at: Optional[str] = Field(default=None, description='CreatedAt holds the value of the "created_at" field.')
    description: Optional[str] = Field(
        default=None,
        description='Description holds the value of the "description" field.',
    )
    edges: Optional[LocationEdges] = Field(
        default=None,
        description="Edges holds the relations/edges for other nodes in the graph.\nThe values are being populated by the LocationQuery when eager-loading is set.",
    )
    id: Optional[str] = Field(default=None, description="ID of the ent.")
    name: Optional[str] = Field(default=None, description='Name holds the value of the "name" field.')
    updated_at: Optional[str] = Field(default=None, description='UpdatedAt holds the value of the "updated_at" field.')


class LocationEdges(BaseModel):
    """Graph edges for the Location ORM entity."""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    children: list[Location] | None = Field(default=None, description="Children holds the value of the children edge.")
    group: Group | None = Field(default=None, description="Group holds the value of the group edge.")
    items: list["Item"] | None = Field(default=None, description="Items holds the value of the items edge.")  # ty: ignore[unresolved-reference]
    parent: Location | None = Field(default=None, description="Parent holds the value of the parent edge.")


class LocationCreate(BaseModel):
    """Request payload for creating a new location."""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    description: Optional[str] = None
    name: Optional[str] = None
    parentId: Optional[str] = None


class LocationSummary(BaseModel):
    """Lightweight location representation used in nested item/location responses."""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    createdAt: Optional[str] = None
    description: Optional[str] = None
    id: Optional[str] = None
    name: Optional[str] = None
    updatedAt: Optional[str] = None


class LocationOutCount(BaseModel):
    """Location summary augmented with an item count, returned by the list endpoint."""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    createdAt: Optional[str] = None
    description: Optional[str] = None
    id: Optional[str] = None
    itemCount: Optional[float] = None
    name: Optional[str] = None
    updatedAt: Optional[str] = None


class LocationUpdate(BaseModel):
    """Request payload for updating an existing location."""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    description: Optional[str] = None
    id: Optional[str] = None
    name: Optional[str] = None
    parentId: Optional[str] = None


class LocationOut(BaseModel):
    """Full location representation returned by location detail endpoints."""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    children: Optional[List[LocationSummary]] = None
    createdAt: Optional[str] = None
    description: Optional[str] = None
    id: Optional[str] = None
    name: Optional[str] = None
    parent: Optional[LocationSummary] = None
    totalPrice: Optional[float] = None
    updatedAt: Optional[str] = None


class TreeItem(BaseModel):
    """A node in the hierarchical location/item tree returned by the tree endpoint."""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    children: Optional[List[TreeItem]] = None
    id: Optional[str] = None
    name: Optional[str] = None
    type: Optional[str] = None


TreeItem.model_rebuild(raise_errors=False)

Location.model_rebuild(raise_errors=False)

__all__ = [
    "LocationCreate",
    "LocationSummary",
    "LocationOutCount",
    "LocationUpdate",
    "LocationOut",
    "TreeItem",
]
