# generated by datamodel-codegen:
#   filename:  document.json

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, ConfigDict, Field


class Location(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    created_at: Optional[str] = Field(
        default=None, description='CreatedAt holds the value of the "created_at" field.'
    )
    description: Optional[str] = Field(
        default=None,
        description='Description holds the value of the "description" field.',
    )
    edges: Optional[LocationEdges] = Field(
        default=None,
        description="Edges holds the relations/edges for other nodes in the graph.\nThe values are being populated by the LocationQuery when eager-loading is set.",
    )
    id: Optional[str] = Field(default=None, description="ID of the ent.")
    name: Optional[str] = Field(
        default=None, description='Name holds the value of the "name" field.'
    )
    updated_at: Optional[str] = Field(
        default=None, description='UpdatedAt holds the value of the "updated_at" field.'
    )


class LocationEdges(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    children: Optional[List[Location]] = Field(
        default=None, description="Children holds the value of the children edge."
    )
    group: Optional[Group] = Field(
        default=None, description="Group holds the value of the group edge."
    )
    items: Optional[List[Item]] = Field(
        default=None, description="Items holds the value of the items edge."
    )
    parent: Optional[Location] = Field(
        default=None, description="Parent holds the value of the parent edge."
    )


class LocationCreate(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    description: Optional[str] = None
    name: Optional[str] = None
    parentId: Optional[str] = None


class LocationSummary(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    createdAt: Optional[str] = None
    description: Optional[str] = None
    id: Optional[str] = None
    name: Optional[str] = None
    updatedAt: Optional[str] = None


class LocationOutCount(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    createdAt: Optional[str] = None
    description: Optional[str] = None
    id: Optional[str] = None
    itemCount: Optional[int] = None
    name: Optional[str] = None
    updatedAt: Optional[str] = None


class LocationUpdate(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    description: Optional[str] = None
    id: Optional[str] = None
    name: Optional[str] = None
    parentId: Optional[str] = None


class LocationOut(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    children: Optional[List[LocationSummary]] = None
    createdAt: Optional[str] = None
    description: Optional[str] = None
    id: Optional[str] = None
    name: Optional[str] = None
    parent: Optional[LocationSummary] = None
    totalPrice: Optional[float] = None
    updatedAt: Optional[str] = None


class TreeItem(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    children: Optional[List[TreeItem]] = None
    id: Optional[str] = None
    name: Optional[str] = None
    type: Optional[str] = None


TreeItem.model_rebuild(raise_errors=False)

Location.model_rebuild(raise_errors=False)

__all__ = [
    "LocationCreate",
    "LocationSummary",
    "LocationOutCount",
    "LocationUpdate",
    "LocationOut",
    "TreeItem",
]
