"""Pydantic models for Homebox maintenance entry resource DTOs."""

# generated by datamodel-codegen:
#   filename:  document.json

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, ConfigDict, Field


class MaintenanceEntry(BaseModel):
    """API DTO for a maintenance log entry returned by maintenance endpoints."""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    completedDate: Optional[str] = None
    cost: Optional[str] = Field(default=None, examples=["0"])
    description: Optional[str] = None
    id: Optional[str] = None
    name: Optional[str] = None
    scheduledDate: Optional[str] = None


class MaintenanceEntryCreate(BaseModel):
    """Request payload for creating a new maintenance log entry."""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    completedDate: Optional[str] = None
    cost: Optional[str] = Field(default=None, examples=["0"])
    description: Optional[str] = None
    name: str
    scheduledDate: Optional[str] = None


class MaintenanceEntryUpdate(BaseModel):
    """Request payload for updating an existing maintenance log entry."""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    completedDate: Optional[str] = None
    cost: Optional[str] = Field(default=None, examples=["0"])
    description: Optional[str] = None
    name: Optional[str] = None
    scheduledDate: Optional[str] = None


class MaintenanceEntryWithDetails(BaseModel):
    """Maintenance log entry augmented with parent item details."""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    completedDate: Optional[str] = None
    cost: Optional[str] = Field(default=None, examples=["0"])
    description: Optional[str] = None
    id: Optional[str] = None
    itemID: Optional[str] = None
    itemName: Optional[str] = None
    name: Optional[str] = None
    scheduledDate: Optional[str] = None


MaintenanceEntry.model_rebuild(raise_errors=False)

__all__ = [
    "MaintenanceEntry",
    "MaintenanceEntryCreate",
    "MaintenanceEntryUpdate",
    "MaintenanceEntryWithDetails",
]
