# generated by datamodel-codegen:
#   filename:  document.json

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, ConfigDict, Field

from .items import ItemCreate


class BarcodeProduct(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    barcode: Optional[str] = None
    imageBase64: Optional[str] = None
    imageURL: Optional[str] = None
    item: Optional[ItemCreate] = None
    manufacturer: Optional[str] = None
    modelNumber: Optional[str] = Field(default=None, description="Identifications")
    notes: Optional[str] = Field(default=None, description="Extras")
    search_engine_name: Optional[str] = None


__all__ = ["BarcodeProduct"]
