"""Pydantic models for Homebox user service DTOs (registration, latest release)."""

# generated by datamodel-codegen:
#   filename:  document.json

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, ConfigDict


class Latest(BaseModel):
    """Latest available Homebox release information embedded in the API summary."""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    date: Optional[str] = None
    version: Optional[str] = None


class UserRegistration(BaseModel):
    """Request payload for registering a new user account."""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    email: Optional[str] = None
    name: Optional[str] = None
    password: Optional[str] = None
    token: Optional[str] = None
