# generated by datamodel-codegen:
#   filename:  document.json

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, ConfigDict


class Latest(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    date: Optional[str] = None
    version: Optional[str] = None


class UserRegistration(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    email: Optional[str] = None
    name: Optional[str] = None
    password: Optional[str] = None
    token: Optional[str] = None
