"""Pydantic models for Homebox user resource DTOs."""

# generated by datamodel-codegen:
#   filename:  document.json

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, ConfigDict, Field

from .auth import AuthTokens
from .types import UserRole


class User(BaseModel):
    """Internal ORM entity representing a Homebox user account."""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    activated_on: Optional[str] = Field(
        default=None,
        description='ActivatedOn holds the value of the "activated_on" field.',
    )
    created_at: Optional[str] = Field(default=None, description='CreatedAt holds the value of the "created_at" field.')
    edges: Optional[UserEdges] = Field(
        default=None,
        description="Edges holds the relations/edges for other nodes in the graph.\nThe values are being populated by "
        "the UserQuery when eager-loading is set.",
    )
    email: Optional[str] = Field(default=None, description='Email holds the value of the "email" field.')
    id: Optional[str] = Field(default=None, description="ID of the ent.")
    is_superuser: Optional[bool] = Field(
        default=None,
        description='IsSuperuser holds the value of the "is_superuser" field.',
    )
    name: Optional[str] = Field(default=None, description='Name holds the value of the "name" field.')
    role: Optional[UserRole] = Field(default=None, description='Role holds the value of the "role" field.')
    superuser: Optional[bool] = Field(default=None, description='Superuser holds the value of the "superuser" field.')
    updated_at: Optional[str] = Field(default=None, description='UpdatedAt holds the value of the "updated_at" field.')


class UserEdges(BaseModel):
    """Graph edges for the User ORM entity."""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    auth_tokens: Optional[list[AuthTokens]] = Field(
        default=None, description="AuthTokens holds the value of the auth_tokens edge."
    )
    group: Optional["Group"] = Field(default=None, description="Group holds the value of the group edge.")  # ty: ignore[unresolved-reference]
    notifiers: Optional[list["Notifier"]] = Field(  # ty: ignore[unresolved-reference]
        default=None, description="Notifiers holds the value of the notifiers edge."
    )


class UserOut(BaseModel):
    """API DTO for a user account returned by user endpoints."""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    defaultGroupId: Optional[str] = None
    email: Optional[str] = None
    groupIds: Optional[list[str]] = None
    groupId: Optional[str] = None
    groupName: Optional[str] = None
    id: Optional[str] = None
    isOwner: Optional[bool] = None
    isSuperuser: Optional[bool] = None
    name: Optional[str] = None
    oidcIssuer: Optional[str] = None
    oidcSubject: Optional[str] = None


class UserSummary(BaseModel):
    """API DTO for lightweight user details in group member listings."""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    email: Optional[str] = None
    id: Optional[str] = None
    isOwner: Optional[bool] = None
    name: Optional[str] = None


class UserUpdate(BaseModel):
    """Request payload for updating the current user's profile."""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    email: str
    name: str


class UserSettings(BaseModel):
    """Arbitrary key/value settings object for the current user."""

    model_config = ConfigDict(
        populate_by_name=True,
        extra="allow",
    )


User.model_rebuild(raise_errors=False)


__all__ = [
    "UserSettings",
    "UserSummary",
    "UserOut",
    "UserUpdate",
]
