# generated by datamodel-codegen:
#   filename:  document.json

from __future__ import annotations

from typing import Annotated, Any, List, Optional

from pydantic import BaseModel, ConfigDict, Field

from . import services


class ActionAmountResult(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    completed: Optional[int] = None


class Build(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    buildTime: Optional[str] = None
    commit: Optional[str] = None
    version: Optional[str] = None


class ChangePassword(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    current: Optional[str] = None
    new: Optional[str] = None


class GroupInvitation(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    expiresAt: Optional[str] = None
    token: Optional[str] = None
    uses: Optional[int] = None


class GroupInvitationCreate(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    expiresAt: Optional[str] = None
    uses: Annotated[int, Field(strict=True, ge=1, le=100)]


class ItemAttachmentToken(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    token: Optional[str] = None


class LoginForm(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    password: Optional[str] = Field(default=None, examples=["admin"])
    stayLoggedIn: Optional[bool] = None
    username: Optional[str] = Field(default=None, examples=["admin@admin.com"])


class TokenResponse(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    attachmentToken: Optional[str] = None
    expiresAt: Optional[str] = None
    token: Optional[str] = None


class Wrapped(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    item: Optional[Any] = None


class APISummary(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    allowRegistration: Optional[bool] = None
    build: Optional[Build] = None
    demo: Optional[bool] = None
    health: Optional[bool] = None
    labelPrinting: Optional[bool] = None
    latest: Optional[services.Latest] = None
    message: Optional[str] = None
    title: Optional[str] = None
    versions: Optional[List[str]] = None
