"""Pydantic models for general Homebox v1 API DTOs (auth, actions, invitations)."""

# generated by datamodel-codegen:
#   filename:  document.json

from __future__ import annotations

from typing import Annotated, Any, List, Optional

from pydantic import BaseModel, ConfigDict, Field

from . import services


class ActionAmountResult(BaseModel):
    """Result of a bulk action endpoint, reporting the number of affected entities."""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    completed: Optional[int] = None


class Build(BaseModel):
    """Build metadata embedded in the API status response."""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    buildTime: Optional[str] = None
    commit: Optional[str] = None
    version: Optional[str] = None


class ChangePassword(BaseModel):
    """Request payload for changing the current user's password."""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    current: Optional[str] = None
    new: Optional[str] = None


class GroupInvitation(BaseModel):
    """Group invitation token returned after a successful invitation creation."""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    expiresAt: Optional[str] = None
    token: Optional[str] = None
    uses: Optional[int] = None


class GroupInvitationCreate(BaseModel):
    """Request payload for creating a new group invitation token."""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    expiresAt: Optional[str] = None
    uses: Annotated[int, Field(strict=True, ge=1, le=100)]


class ItemAttachmentToken(BaseModel):
    """Short-lived token for downloading an item attachment without a Bearer token."""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    token: Optional[str] = None


class LoginForm(BaseModel):
    """Request payload for the user login endpoint."""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    password: Optional[str] = Field(default=None, examples=["admin"])
    stayLoggedIn: Optional[bool] = None
    username: Optional[str] = Field(default=None, examples=["admin@admin.com"])


class OIDCStatus(BaseModel):
    """OIDC availability/configuration summary exposed by the status endpoint."""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    allowLocal: Optional[bool] = None
    autoRedirect: Optional[bool] = None
    buttonText: Optional[str] = None
    enabled: Optional[bool] = None


class TokenResponse(BaseModel):
    """Authentication token response returned after a successful login or refresh."""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    attachmentToken: Optional[str] = None
    expiresAt: Optional[str] = None
    token: Optional[str] = None


class Wrapped(BaseModel):
    """Generic wrapper model that contains a single ``item`` field of any type."""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    item: Optional[Any] = None


class APISummary(BaseModel):
    """Summary of the running Homebox application returned by ``/v1/status``."""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    allowRegistration: Optional[bool] = None
    build: Optional[Build] = None
    demo: Optional[bool] = None
    health: Optional[bool] = None
    labelPrinting: Optional[bool] = None
    latest: Optional[services.Latest] = None
    message: Optional[str] = None
    oidc: Optional[OIDCStatus] = None
    title: Optional[str] = None
    versions: Optional[List[str]] = None
