"""Pydantic model for Homebox API error response payloads."""

# generated by datamodel-codegen:
#   filename:  document.json

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, ConfigDict


class ErrorResponse(BaseModel):
    """Standard error response body returned by the API on validation failures."""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    error: Optional[str] = None
    fields: Optional[str] = None
