"""Example script that shows how to attach files to entities in Homebox.

The script creates a location-like entity and an item-like child entity, then
uploads, lists, downloads, updates, and deletes attachments.

In order to run this script, you need to have the following environment variables set:
- HOMEBOX_URL: the URL of your Homebox instance (e.g. http://localhost
- HOMEBOX_USERNAME: the username of a user with permissions to create entities
- HOMEBOX_PASSWORD: the password of that user

You can use the .env.sample file in the examples directory as a template for your .env file.
"""

from __future__ import annotations

import base64
import os
from datetime import UTC, datetime
from pathlib import Path

from _v26 import require_entity_type, require_id

from homebox import HomeboxClient
from homebox.models import EntityCreate, ItemAttachmentUpdate


def _load_dotenv() -> None:
    dotenv_path = Path(__file__).parent / ".env"
    if not dotenv_path.is_file():
        return

    with dotenv_path.open() as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            if "=" not in line:
                continue
            key, value = line.split("=", 1)
            os.environ.setdefault(key.strip(), value.strip())


def _require_env(name: str) -> str:
    value = os.getenv(name)
    if not value:
        raise RuntimeError(f"Missing required environment variable: {name}")
    return value


def _build_client() -> HomeboxClient:
    base_url = _require_env("HOMEBOX_URL")
    username = _require_env("HOMEBOX_USERNAME")
    password = _require_env("HOMEBOX_PASSWORD")

    client = HomeboxClient(base_url=base_url)
    client.login(username, password)
    return client


def _tiny_png() -> bytes:
    return base64.b64decode(
        "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO7+X0kAAAAASUVORK5CYII="
    )


def main() -> None:
    _load_dotenv()
    client = _build_client()

    suffix = datetime.now(UTC).strftime("%Y%m%d_%H%M%S")
    location_type = require_entity_type(client, is_location=True)
    item_type = require_entity_type(client, is_location=False)
    created_location_id: str | None = None
    created_entity_id: str | None = None

    try:
        location = client.entities.create_entity(
            EntityCreate(
                name=f"Attachment Demo {suffix}",
                description="Created by item_attachements.py",
                entityTypeId=location_type.id,
            )
        )
        created_location_id = require_id(location.id, resource="Location entity")
        entity = client.entities.create_entity(
            EntityCreate(
                name=f"Attachment Entity {suffix}",
                description="Entity used for attachment demo",
                entityTypeId=item_type.id,
                parentId=created_location_id,
            )
        )
        created_entity_id = require_id(entity.id, resource="Attachment entity")

        print(f"Created location: {location.id}")
        print(f"Created entity: {entity.id}")

        client.entities.create_attachment(
            created_entity_id,
            file=b"This is a text attachment generated by the example script.\n",
            type="manual",
            primary=False,
            name="readme.txt",
        )
        client.entities.create_attachment(
            created_entity_id,
            file=_tiny_png(),
            type="photo",
            primary=True,
            name="preview.png",
        )
        print("Uploaded two attachments")

        entity_with_attachments = client.entities.get_entity(created_entity_id)
        attachments = entity_with_attachments.attachments or []
        print(f"Entity {entity.name} has {len(attachments)} attachment(s):")
        for att in attachments:
            print(f"- id={att.id}, title={att.title}, type={att.type}, primary={att.primary}")

        if not attachments or not attachments[0].id:
            print("No downloadable attachment found.")
            return

        # Download the first attachment.
        attachment_id = attachments[0].id
        attachment_data = client.entities.get_attachment(created_entity_id, attachment_id)
        if not attachment_data:
            print("Attachment endpoint returned no data.")
            return

        output_file = Path.cwd() / f"downloaded_{attachment_id[:8]}"
        output_file.write_bytes(attachment_data)
        print(f"Downloaded attachment to {output_file}")

        # Update the title of the first attachment.
        updated_entity = client.entities.update_attachment(
            created_entity_id,
            attachment_id,
            ItemAttachmentUpdate(title="Updated readme", type="manual", primary=False),
        )
        updated_attachments = updated_entity.attachments or []
        renamed = next((a for a in updated_attachments if a.id == attachment_id), None)
        if renamed:
            print(f"Updated attachment title to: {renamed.title}")

        # Delete the second attachment if present.
        if len(attachments) > 1 and attachments[1].id:
            client.entities.delete_attachment(created_entity_id, attachments[1].id)
            print(f"Deleted attachment: {attachments[1].id}")

    finally:
        if created_entity_id:
            client.entities.delete_entity(created_entity_id)
            print(f"Deleted entity: {created_entity_id}")

        if created_location_id:
            client.entities.delete_entity(created_location_id)
            print(f"Deleted location: {created_location_id}")


if __name__ == "__main__":
    main()
